version: '3'

name: mlops-stack
services:
  mlflow:
    build: ./mlflow
    image: mlflow
    container_name: mlflow_mlops
    ports:
      - ${MLFLOW_HOST_PORT}:${MLFLOW_CONT_PORT}
    volumes:
      - ${MLFLOW_HOST_CONFIG_PATH}:${MLFLOW_CONT_CONFIG_PATH}
      - ./mlflow_data:/mlflow/mlflow_data
      - ./mlflow_artifacts:/mlflow/mlflow_artifacts
    environment:
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
      - MLFLOW_BACKEND_STORE_URI=sqlite:////mlflow/mlflow_data/mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=file:///mlflow/mlflow_artifacts
      - MLFLOW_FLASK_SERVER_SECRET_KEY=${MLFLOW_FLASK_SERVER_SECRET_KEY}
    restart: unless-stopped

volumes:
  mlflow_data:
  mlflow_artifacts: