apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release_name }}
  labels:
    app: {{ .Values.release_name }}
spec:
  type: {{ .Values.datasetGenService.service.type }}
  ports:
  - port: {{ .Values.datasetGenService.service.port }}
    targetPort: {{ .Values.datasetGenService.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.release_name }}
