-- liquibase formatted sql

-- changeset Erangi Ariyasena:classifier-script-v13-changeset1
CREATE TYPE Training_Progress_Status AS ENUM ('Initiating Training', 'Training In-Progress', 'Deploying Model', 'Model Trained And Deployed','Training Failed');

-- changeset Erangi Ariyasena:classifier-script-v13-changeset2
CREATE TABLE model_progress_sessions (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    model_id BIGINT NOT NULL,
    model_name TEXT NOT NULL,
    major_version INT NOT NULL DEFAULT 0,
    minor_version INT NOT NULL DEFAULT 0,
    latest BOOLEAN DEFAULT false,
    process_complete BOOLEAN DEFAULT false,
    progress_percentage INT,
    training_progress_status Training_Progress_Status,
    training_message TEXT ,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT model_progress_sessions_pkey PRIMARY KEY (id)
);