-- liquibase formatted sql

-- changeset erangi:global-classifier classification-feedback-table
CREATE TABLE public.classification_feedback (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    chat_id VARCHAR(255) NOT NULL,
    inference_id VARCHAR(255) NOT NULL,
    actual_agency_id VARCHAR(255) NOT NULL,
    feedback_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT classification_feedback_pkey PRIMARY KEY (id),
    CONSTRAINT unique_feedback_per_inference UNIQUE (inference_id)
);
