-- liquibase formatted sql

-- changeset erangi:global-classifier-integrated-agency-enums
-- Create model status enum
CREATE TYPE model_status AS ENUM ('active', 'deprecated');

-- Create training status enum
CREATE TYPE training_status AS ENUM ('retraining_needed', 'trained', 'training_in_progress', 'training_failed', 'not_trained');

-- Create deployment environment enum
CREATE TYPE deployment_environment AS ENUM ('undeployed', 'testing', 'production');

CREATE TYPE base_models AS ENUM ('distil-bert', 'roberta', 'bert');


-- changeset erangi:global-classifier-data-models-table
CREATE TABLE public.data_models (
    model_id BIGSERIAL PRIMARY KEY,
    model_name VARCHAR(255) NOT NULL,
    major INTEGER NOT NULL,
    minor INTEGER NOT NULL,
    dataset_id VARCHAR(255) NOT NULL,
    dataset_version VARCHAR(255),
    base_models VARCHAR(255)[] NOT NULL,
    deployment_environment VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_trained TIMESTAMP WITH TIME ZONE,
    model_status VARCHAR(64),
    training_status VARCHAR(64)
)

-- changeset erangi:global-classifier-model_configurations
CREATE TABLE model_configurations (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    base_models base_models[],
    deployment_environments deployment_environment[],
    CONSTRAINT model_configurations_pkey PRIMARY KEY (id)
);

-- changeset erangi:global-classifier-model_configurations-add-data
INSERT INTO model_configurations (base_models, deployment_environments) VALUES
(
    ARRAY['distil-bert', 'roberta', 'bert']::base_models[],
    ARRAY['undeployed', 'testing', 'production']::deployment_environment[]
);