-- liquibase formatted sql

-- changeset erangi:global-classifier-integrated-agency-enums
-- Create model status enum
CREATE TYPE model_status AS ENUM ('active', 'deprecated');

-- Create training status enum
CREATE TYPE training_status AS ENUM ('retraining_needed', 'trained', 'training_in_progress', 'training_failed', 'initiating_training');

-- Create deployment environment enum
CREATE TYPE deployment_environment AS ENUM ('undeployed', 'testing', 'production');

CREATE TYPE base_models AS ENUM ('distil-bert', 'roberta', 'bert');

-- changeset erangi:global-classifier-models-metadata-table
CREATE TABLE public.data_models (
    model_id BIGSERIAL PRIMARY KEY,
    model_group_key VARCHAR(255) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    major INTEGER NOT NULL,
    minor INTEGER NOT NULL,
    latest BOOLEAN DEFAULT false,
    deployment_env deployment_environment NOT NULL,
    training_status training_status DEFAULT 'initiating_training',
    base_models JSONB NOT NULL,
    last_trained TIMESTAMP WITH TIME ZONE,
    connected_ds_id BIGINT NOT NULL,
    connected_ds_major_version INTEGER,
    connected_ds_minor_version INTEGER,
    model_status model_status DEFAULT 'active',
    model_s3_location VARCHAR(2048),
    training_results JSONB,
    created_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- changeset erangi:global-classifier-model_configurations
CREATE TABLE model_configurations (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    base_models JSONB,
    deployment_environments deployment_environment[],
    CONSTRAINT model_configurations_pkey PRIMARY KEY (id)
);

-- changeset erangi:global-classifier-model_configurations-add-data
INSERT INTO model_configurations (base_models, deployment_environments) VALUES
(
    '["distil-bert", "roberta", "bert"]'::JSONB,
    ARRAY['undeployed', 'testing', 'production']::deployment_environment[]
);