{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.release_name }}"
  labels:
    app: "{{ .Values.release_name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.release_name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.release_name }}"
    spec:
      initContainers:
       - name: git-clone
         image: alpine/git:latest
         volumeMounts:
          - name: dsl
            mountPath: /workspace/app/module
         command:
            - sh
            - -c
            - |
                git clone --single-branch --depth 1 --branch dev  https://github.com/rootcodelabs/Global-Classifier.git /tmp/ckb &&

                cp -r /tmp/ckb/DSL/DMapper/global-classifier/* /workspace/app/module
      containers:
        - name: "{{ .Values.release_name }}"
          image: "{{ .Values.images.scope.registry }}/{{ .Values.images.scope.repository }}:{{ .Values.images.scope.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: CONTENT_FOLDER
              value: "{{ .Values.env.CONTENT_FOLDER }}"
          volumeMounts:
            - name: dsl
              mountPath: /workspace/app/module
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
      volumes:
        - name: dsl
          emptyDir: {}
{{- end }}